### ISSUE TITLE
Upgrade node to node 16+

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/ysm#183]
### Overview
We need to upgrade our node version to 16+ [because GitHub actions will no longer support lower versions](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/#:~:text=GitHub%20Actions%3A%20All%20Actions%20will%20begin%20running%20on%20Node16%20instead%20of%20Node12,-actions&text=Node%2012%20has%20been%20out,on%20Node16%20by%20Summer%202023.).

### Action Items
- [x] Upgrade node to 16+ or highest version as possible without affecting other packages.
- [ ] Ensure all other dependencies are compatible with node 16+, upgrade them if necessary. 
- [x] Test by checking if happy paths work.

Note: This upgrade may not be possible or might require more steps than listed here. Will update this issue accordingly.

### Resources
- [Happy paths guide to YSM](https://chayn.notion.site/YSM-Happy-Paths-ede713cd587b4e949e47634d9997a585?pvs=4)

**Comment by eleanorreem** [comment]
@kyleecodes we can probably delete and rewrite this ticket

**Comment by kyleecodes** [comment]
Happy paths, dev builds, and local production builds are successful when upgrading to version 16 of node.

However there are 2 setbacks:
1. `yarn audit` yields critical vulnerabilities where upgrading NextJS and React are necessary, requiring more significant code changes, as [React18 is not compatible with important dependencies, such as `react-dom'](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis). I could make these into separate issues.
2. 1 unit test fails (`src/tests/SaveButton.test.js`) when upgrading to node 16 [as seen in this PR](https://github.com/chaynHQ/ysm/pull/201/checks):
```
TypeError: user.getIdToken is not a function
    at getIdToken (/home/neo/chayn/workflows/ysm/src/components/SaveButton.js:77:44)
```
The error appears to be caught [here](https://github.com/chaynHQ/ysm/blob/3832cb448e3be8f1def80ca88cca391f8bdfb6cc/src/config/firebase.js#L50)  in `firebase.js`. 

@eleanorreem I am going to revisit this issue after completing other tasks.

**Comment by eleanorreem** [comment]
@kyleecodes  this has been done by @annarhughes
