### ISSUE TITLE
Remove Snyk as a Dependency manager

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/ysm#198]
### Overview
 Ideally we would just be using dependabot like the rest of our ecosystem. Dependabot is the default manager for github so we would like to remove Snyk.

### Action Items

- [x]  Research how to remove Snyk from github repositories. See resources below. 
- [x]  Implement steps recommended in your research
If you come across difficulties please tag @eleanorreem in this issue. 

### Resources
https://docs.snyk.io/integrations/git-repository-scm-integrations/introduction-to-git-repository-integrations/disable-a-git-integration

**Comment by kyleecodes** [comment]
The resource above provides directions for disabling Snyk in Git version control, to remove Snyk on GitHub, [we can revoke Snyk's access through on GitHub.](https://docs.snyk.io/integrations/git-repository-scm-integrations/snyk-github-integration#how-to-disable-the-snyk-github-integration)

First, I disabled Snyk's webhooks in this repo settings. Next, I disabled Snyk's third-party access in our organization settings. Snyk should no longer be enabled in our ecosystem!

Next I can enable dependabot again and clean up old PRs from Snyk.
