### ISSUE TITLE
Bump firebase from from 9.9.4 to 10.2.0

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/ysm#207]
### Overview
We need to upgrade from firebase 9.9.4 to 10.2.0, as directed in this [pull request](https://github.com/chaynHQ/ysm/pull/196).

### Action Items

- [ ] Follow the Contributing Guidelines in the [CONTRIBUTING.md](https://github.com/chaynHQ/ysm/blob/master/CONTRIBUTING.md) file for how to fork, branch, and commit properly to Chayn's projects.
- [ ] Run both ysm (this repo) and [ysm-backend](https://github.com/chaynHQ/ysm-backend) to ensure that this change in dependency has not affected the application.
- [ ] Run unit tests commands found in the [README.md](https://github.com/chaynHQ/ysm/blob/master/README.md) file to ensure they're all passing.

Please report progress here. Thank you!

**Comment by kyleecodes** [comment]
Hey @sonvir249, thank you for your interest in contributing to Chayn!

We ask that our contributors asked to be assigned issues before opening PRs for them, as per our CONTRIBUTING.md. This helps us keep track of who is working on what. I'll assign you this issue. 

Quick question about your PR, did you go through the to-do steps listed here? Thanks again!

**Comment by sonvir249** [comment]
@kyleecodes Thank you for your feedback! I apologize for missing that step. I'll be sure to follow the process in the future. Yes, I've gone through the to-do steps and believe the changes are ready for review. Looking forward to your feedback. Thanks again!

**Comment by kyleecodes** [comment]
@sonvir249 I've assigned you the issue, your pull request looked good to me! Ready to merge if you reopen. :D

**Comment by sonvir249** [comment]
@kyleecodes I might need to raise another PR, looks like the PR is closed, because I deleted the forked repository.

**Comment by sonvir249** [comment]
@kyleecodes Please review https://github.com/chaynHQ/ysm/pull/216
