### ISSUE TITLE
Improve UI on desktop screens

### ISSUE THREAD

**Issue by Keith-Web3** [chaynHQ/ysm#214]
### Overview
We need to improve the UI of the frontend app on desktop screens. It currently doesn't look too good.
Currently, it looks like this
![Screenshot (316)](https://github.com/chaynHQ/ysm/assets/96974022/2b432acd-4642-4d7f-a29e-c3eacefffcf7)

### Action Items
Remove scrollbars showing up in the container element

**Comment by kyleecodes** [comment]
Hey @Keith-Web3!👋

Thank you for creating this issue! I agree the desktop UI can be improved! However, where scrolling is necessary, we will keep them for accessibility reasons. But the design can be improved upon! For instance:

- [ ] Remove horizontal scrolling 
- [ ] Responsively move scrollbars when all content is visible
- [ ] Make aesthetic changes while complying with Chayn's theme and accessible GUI standards - make scrollbars look like scrollbars, function intuitively, contrast not too high
- [ ] Move most important information above the scroll to improve viewer retention

More resources here:
https://www.nngroup.com/articles/scrolling-and-scrollbars/
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/scrollbar_role
https://ux.stackexchange.com/questions/33384/accessible-custom-scrollbars

If you would like to complete any of the steps above, I'll assign you this issue.

Thanks again!

**Comment by Keith-Web3** [comment]
Yeah, I would like to work on the issue.

**Comment by kyleecodes** [comment]
Great! @Keith-Web3 you are assigned.

We are currently in the process of updating this app entirely, from the docs to the dependencies. If you encounter any difficulties, please reach out here we'll be happy to help! Your feedback is highly appreciated.

**Comment by Keith-Web3** [comment]
@kyleecodes I noticed some of the packages were installed as far back as three years ago and it's causing some install conflicts. I guess this would be fixed in the ongoing update so should I hold the UI changes till the updates are done?

**Comment by kyleecodes** [comment]
@Keith-Web3 thank you for your patience! We had to wait another week to begin upgrading this project, but we are back now and I just saw your message.

If none of these install conflicts interrupt your ability to work on the UI, I would ignore them. However, if these install conflicts interfere with editing the UI, please report them here. Some may be quick fixes, but if not, I can troubleshoot the issues here or open new issues for solving these conflicts. 

Can you share a screenshot or copy-paste the install conflicts you're experiencing? Thanks again.

**Comment by kyleecodes** [comment]
Hey @Keith-Web3, we have decided to archive this repo and Your Story Matters. I'm unassigning you this issue. 

We invite you to extend your ideas to our newer open-source project, [Bloom](https://github.com/chaynHQ/bloom-frontend), which is similar to this project, but with more features and actively maintained! 

Check out Bloom here: https://github.com/chaynHQ/bloom-frontend

Thank you for your interest!

**Comment by Keith-Web3** [comment]
Alright, cool. I'll check it out
